### ISSUE TITLE
Problème de rebond dans les collisions

### ISSUE THREAD

**Issue by Skolopedrion** [Loodoor/Unamed#1]
Le joueur rebondis contre un obstacle lorsqu'on marche dans deux cas:
- Si le joueur marche vers le haut et rencontre un obstacle en haut à droite.
- Si le joueur marche vers la gauche et rencontre un obstacle en bas à droite.

Je pense que c'est dû à un souci d'arrondissement à l'entier inférieur des coordonnées du joueur.

**Comment by Loodoor** [comment]
J'vais tenter un fix à coup de math.ceil et math.floor ;)
